<?php
/**
 * Project: FreelancerBidder
 *
 * @author Amado Martinez <amado@projectivemotion.com>
 */

namespace Projectivemotion\FreelancerBidder;
use Projectivemotion\FreelancerBidder\Commands\FindProjects;
use Projectivemotion\FreelancerBidder\Commands\FindProjectsFreelancer;
use Projectivemotion\FreelancerBidder\Commands\FindProjectsUpWork;
use Projectivemotion\FreelancerBidder\Commands\ImportProjects;


class Application extends  \Symfony\Component\Console\Application
{

    static function getEntityManager()
    {
        $devMode = true;
        $config = \Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration([__DIR__], $devMode);

        $conn   =   ['driver' => 'pdo_sqlite', 'path' => __DIR__ . '/../../app/db.sqlite'];

        $entityManager = \Doctrine\ORM\EntityManager::create($conn, $config);
        return $entityManager;
    }

    protected function getDefaultCommands()
    {
        $commands = parent::getDefaultCommands(); // TODO: Change the autogenerated stub
        $commands[] = new FindProjectsFreelancer();
        $commands[] = new FindProjectsUpWork();
        $commands[] = new ImportProjects();
        return $commands;
    }


}